spring.application.name=scrapper
spring.config.import=optional:file:.env[.properties]

app.markets[0].country-name=BRAZIL
app.markets[0].country-code=BR
app.markets[0].stocks=CASH3,BBAS3,PETR4,VALE3
app.markets[0].market-name=IBOVESPA
app.markets[0].market-ticker=SA
app.markets[0].currency=BRL

app.markets[1].country-name=UNITED STATES OF AMERICA
app.markets[1].country-code=US
app.markets[1].stocks=AAPL,MSFT,GOOG,AMZN
app.markets[1].market-name=NASDAQ
app.markets[1].market-ticker=
app.markets[1].currency=USD

app.markets[2].country-name=AUSTRALIA
app.markets[2].country-code=AU
app.markets[2].stocks=CBA,BHP,WOW,ASX
app.markets[2].market-name=ASX
app.markets[2].market-ticker=AX
app.markets[2].currency=AUD

app.crypto=BTC,ETH,LTC

app.rapid-api-key=${RAPID_API_KEY}
app.rapid-api-host=${RAPID_API_HOST}
app.rapid-api-base-url=https://${RAPID_API_HOST}
app.rapid-api-version=${RAPID_API_VERSION}
