spring.application.name=scrapper

app.markets[0].country=BR
app.markets[0].stocks=CASH3,BBAS3,PETR4,VALE3
app.markets[0].market=SA
app.markets[0].currency=BRL

app.markets[1].country=US
app.markets[1].stocks=AAPL,MSFT,GOOG,AMZN
app.markets[1].currency=USD
app.markets[1].market=

app.markets[2].country=AU
app.markets[2].stocks=CBA,BHP,WOW,ASX
app.markets[2].market=AX
app.markets[2].currency=AUD

app.crypto=BTC,ETH,LTC