CREATE TABLE country
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    code VARCHAR(255),
    CONSTRAINT pk_country PRIMARY KEY (id)
);

CREATE TABLE crypto
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    price       DOUBLE PRECISION                        NOT NULL,
    currency    VARCHAR(255),
    last_update TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_crypto PRIMARY KEY (id)
);

CREATE TABLE crypto_price
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    priceusd  DOUBLE PRECISION                        NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE,
    crypto_id BIGINT,
    CONSTRAINT pk_crypto_price PRIMARY KEY (id)
);

CREATE TABLE currency
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    code       VARCHAR(255),
    country_id BIGINT,
    CONSTRAINT pk_currency PRIMARY KEY (id)
);

CREATE TABLE market
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    code       VARCHAR(255),
    country_id BIGINT,
    stock_id   BIGINT,
    CONSTRAINT pk_market PRIMARY KEY (id)
);

CREATE TABLE stock
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    company_name   VARCHAR(255),
    company_ticker VARCHAR(255),
    CONSTRAINT pk_stock PRIMARY KEY (id)
);

CREATE TABLE stock_price
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    priceusd  DOUBLE PRECISION                        NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE,
    stock_id  BIGINT,
    CONSTRAINT pk_stock_price PRIMARY KEY (id)
);

CREATE TABLE usd_exchange_rate
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rate_integer DOUBLE PRECISION                        NOT NULL,
    timestamp    TIMESTAMP WITHOUT TIME ZONE,
    currency_id  BIGINT,
    CONSTRAINT pk_usd_exchange_rate PRIMARY KEY (id)
);

ALTER TABLE currency
    ADD CONSTRAINT uc_currency_country UNIQUE (country_id);

ALTER TABLE market
    ADD CONSTRAINT uc_market_stock UNIQUE (stock_id);

CREATE INDEX idx_crypto_currency ON crypto (currency);

CREATE INDEX idx_crypto_name ON crypto (name);

CREATE INDEX idx_usd_exchange_rate_timestamp ON usd_exchange_rate (timestamp);

ALTER TABLE crypto_price
    ADD CONSTRAINT FK_CRYPTO_PRICE_ON_CRYPTO FOREIGN KEY (crypto_id) REFERENCES crypto (id);

ALTER TABLE currency
    ADD CONSTRAINT FK_CURRENCY_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES country (id);

ALTER TABLE market
    ADD CONSTRAINT FK_MARKET_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES country (id);

ALTER TABLE market
    ADD CONSTRAINT FK_MARKET_ON_STOCK FOREIGN KEY (stock_id) REFERENCES stock (id);

ALTER TABLE stock_price
    ADD CONSTRAINT FK_STOCK_PRICE_ON_STOCK FOREIGN KEY (stock_id) REFERENCES stock (id);

ALTER TABLE usd_exchange_rate
    ADD CONSTRAINT FK_USD_EXCHANGE_RATE_ON_CURRENCY FOREIGN KEY (currency_id) REFERENCES currency (id);

CREATE INDEX idx_usd_exchange_rate_currency ON usd_exchange_rate (currency_id);